"""add column

Revision ID: 0a1906f61b2c
Revises: 855e9b2a25f5
Create Date: 2025-01-13 12:40:33.155869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a1906f61b2c'
down_revision: Union[str, None] = '855e9b2a25f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('texts', sa.Column('audio_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('texts', 'audio_path')
    # ### end Alembic commands ###
