"""add audio_path

Revision ID: 230852c3f6fa
Revises: d302297bad73
Create Date: 2025-01-13 15:40:02.372867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230852c3f6fa'
down_revision: Union[str, None] = 'd302297bad73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('texts', sa.Column('audio_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('texts', 'audio_path')
    # ### end Alembic commands ###
