"""Initial migration

Revision ID: cdb269538e8d
Revises: 
Create Date: 2025-01-11 11:54:52.699033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdb269538e8d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_voice_recordings_filename', table_name='voice_recordings')
    op.drop_index('ix_voice_recordings_id', table_name='voice_recordings')
    op.drop_index('ix_voice_recordings_transcription', table_name='voice_recordings')
    op.drop_table('voice_recordings')
    op.drop_index('ix_texts_id', table_name='texts')
    op.drop_table('texts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('texts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=False),
    sa.Column('audio_data', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_texts_id', 'texts', ['id'], unique=False)
    op.create_table('voice_recordings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(), nullable=True),
    sa.Column('voice_data', sa.BLOB(), nullable=True),
    sa.Column('transcription', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_voice_recordings_transcription', 'voice_recordings', ['transcription'], unique=False)
    op.create_index('ix_voice_recordings_id', 'voice_recordings', ['id'], unique=False)
    op.create_index('ix_voice_recordings_filename', 'voice_recordings', ['filename'], unique=False)
    # ### end Alembic commands ###
