"""remove audio_path

Revision ID: d302297bad73
Revises: 0a1906f61b2c
Create Date: 2025-01-13 12:43:00.214468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd302297bad73'
down_revision: Union[str, None] = '0a1906f61b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('texts', 'audio_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('texts', sa.Column('audio_path', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
